# ========== PPM MICROSCOPE CONFIGURATION ==========
# References hardware from resources_LOCI.yml

microscope:
  name: 'PPM'
  type: 'UprightBrightfield'
  detector_in_use: null
  objective_in_use: null
  modality: null

# ========== MODALITY-SPECIFIC SETTINGS ==========
modalities:
  ppm:
    type: 'polarized'
    rotation_stage:
      device: 'LOCI_STAGE_THORLABS_001'
      type: 'polarizer'
    rotation_angles:
      - name: 'negative'
        tick: -5  # 1 tick = 2 degrees
      - name: 'crossed'
        tick: 0   # 1 tick = 2 degrees
      - name: 'positive'
        tick: 5   # 1 tick = 2 degrees
      - name: 'uncrossed'
        tick: 90  # 1 tick = 2 degrees
    background_correction:
      enabled: true
      method: 'divide'
      base_folder: "D:/2025QPSC/data/background_tiles"
        
  brightfield:
    type: 'brightfield'
    background_correction:
      enabled: true
      method: 'divide'
      base_folder: "D:/2025QPSC/data/background_tiles"

# ========== ACQUISITION PROFILES ==========
acq_profiles_new:
  defaults:
    # Default settings by objective that apply unless overridden in specific profile
    - objective: 'LOCI_OBJECTIVE_OLYMPUS_10X_001'
      settings:
        autofocus:
          n_steps: 9
          search_range_um: 50
          n_tiles: 5
        pixel_size_xy_um:
          LOCI_DETECTOR_TELEDYNE_001: 0.4537  # MicroPublisher 6
          LOCI_DETECTOR_JAI_001: 0.6866       # JAI prism detector
          
    - objective: 'LOCI_OBJECTIVE_OLYMPUS_20X_POL_001'
      settings:
        autofocus:
          n_steps: 11
          search_range_um: 25
          n_tiles: 5
        pixel_size_xy_um:
          LOCI_DETECTOR_TELEDYNE_001: 0.2271
          LOCI_DETECTOR_JAI_001: 0.3433
          
    - objective: 'LOCI_OBJECTIVE_OLYMPUS_40X_POL_001'
      settings:
        autofocus:
          n_steps: 15
          search_range_um: 10
          n_tiles: 7
        pixel_size_xy_um:
          LOCI_DETECTOR_TELEDYNE_001: 0.1142
          LOCI_DETECTOR_JAI_001: 0.1709

  profiles:
    # ===== PPM 10x PROFILES =====
    - modality: 'ppm'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_10X_001'
      detector: 'LOCI_DETECTOR_TELEDYNE_001'
      settings:
        exposures_ms:
          negative: 500
          crossed: 800
          positive: 500
          uncrossed: 10
        gains:  # Constant RGB gains for this detector
          r: 1.2
          g: 1.0
          b: 1.1
          
    - modality: 'ppm'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_10X_001'
      detector: 'LOCI_DETECTOR_JAI_001'
      settings:
        exposures_ms:
          negative:
            all: 500
            r: 450
            g: 500
            b: 550
          crossed:
            all: 800
            r: 750
            g: 800
            b: 850
          positive:
            all: 500
            r: 450
            g: 500
            b: 550
          uncrossed:
            all: 10
            r: 8
            g: 10
            b: 12
        gains:  # Angle-specific RGB gains for JAI
          negative: {r: 1.0, g: 1.0, b: 1.0}
          crossed: {r: 1.1, g: 1.0, b: 1.05}
          positive: {r: 1.0, g: 1.0, b: 1.0}
          uncrossed: {r: 1.2, g: 1.0, b: 1.1}
          
    # ===== PPM 20x PROFILES =====
    - modality: 'ppm'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_20X_POL_001'
      detector: 'LOCI_DETECTOR_TELEDYNE_001'
      settings:
        exposures_ms:
          negative: 800
          crossed: 1200
          positive: 800
          uncrossed: 15
        gains:
          r: 1.2
          g: 1.0
          b: 1.1
          
    - modality: 'ppm'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_20X_POL_001'
      detector: 'LOCI_DETECTOR_JAI_001'
      settings:
        exposures_ms:
          negative:
            all: 800
            r: 750
            g: 800
            b: 850
          crossed:
            all: 1200
            r: 1150
            g: 1200
            b: 1250
          positive:
            all: 800
            r: 750
            g: 800
            b: 850
          uncrossed:
            all: 15
            r: 12
            g: 15
            b: 18
        gains:
          negative: {r: 1.0, g: 1.0, b: 1.0}
          crossed: {r: 1.1, g: 1.0, b: 1.05}
          positive: {r: 1.0, g: 1.0, b: 1.0}
          uncrossed: {r: 1.2, g: 1.0, b: 1.1}
          
    # ===== PPM 40x PROFILES =====
    - modality: 'ppm'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_40X_POL_001'
      detector: 'LOCI_DETECTOR_TELEDYNE_001'
      settings:
        exposures_ms:
          negative: 1500
          crossed: 2000
          positive: 1500
          uncrossed: 25
        gains:
          r: 1.2
          g: 1.0
          b: 1.1
          
    - modality: 'ppm'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_40X_POL_001'
      detector: 'LOCI_DETECTOR_JAI_001'
      settings:
        exposures_ms:
          negative:
            all: 1500
            r: 1450
            g: 1500
            b: 1550
          crossed:
            all: 2000
            r: 1950
            g: 2000
            b: 2050
          positive:
            all: 1500
            r: 1450
            g: 1500
            b: 1550
          uncrossed:
            all: 25
            r: 22
            g: 25
            b: 28
        gains:
          negative: {r: 1.0, g: 1.0, b: 1.0}
          crossed: {r: 1.1, g: 1.0, b: 1.05}
          positive: {r: 1.0, g: 1.0, b: 1.0}
          uncrossed: {r: 1.2, g: 1.0, b: 1.1}
          
    # ===== BRIGHTFIELD PROFILES =====
    - modality: 'brightfield'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_10X_001'
      detector: 'LOCI_DETECTOR_TELEDYNE_001'
      settings:
        exposures_ms:
          single: 50  # Single exposure for brightfield
        gains:
          r: 1.2
          g: 1.0
          b: 1.1
          
    - modality: 'brightfield'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_10X_001'
      detector: 'LOCI_DETECTOR_JAI_001'
      settings:
        exposures_ms:
          single: 50
        gains:
          single: 1.0  # Single gain value for all channels
          
    - modality: 'brightfield'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_20X_POL_001'
      detector: 'LOCI_DETECTOR_TELEDYNE_001'
      settings:
        exposures_ms:
          single: 80
        gains:
          r: 1.2
          g: 1.0
          b: 1.1
          
    - modality: 'brightfield'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_20X_POL_001'
      detector: 'LOCI_DETECTOR_JAI_001'
      settings:
        exposures_ms:
          single: 80
        gains:
          single: 1.0
          
    - modality: 'brightfield'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_40X_POL_001'
      detector: 'LOCI_DETECTOR_TELEDYNE_001'
      settings:
        exposures_ms:
          single: 120
        gains:
          r: 1.2
          g: 1.0
          b: 1.1
          
    - modality: 'brightfield'
      objective: 'LOCI_OBJECTIVE_OLYMPUS_40X_POL_001'
      detector: 'LOCI_DETECTOR_JAI_001'
      settings:
        exposures_ms:
          single: 120
        gains:
          single: 1.0

# ========== STAGE CONFIGURATION ==========
stage:
  stage_id: 'LOCI_STAGE_PRIOR_001'  # Prior XYZ stage
  limits:
    x_um:
      low: -17000
      high: 33000
    y_um:
      low: -12000
      high: 13000
    z_um:
      low: -1800
      high: 100

# ========== GENERAL SETTINGS ==========
slide_size_um:
  x: 40000
  y: 20000