name: Java CI with Gradle

on:
  workflow_dispatch:  # Only manual trigger, removes automatic triggers

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: false  # This ensures it never runs even if manually triggered
    steps:
      - run: echo "Workflow disabled for internal testing"